image:
  repository: velero/velero
  tag: v1.4.0
  pullPolicy: IfNotPresent
initContainers:
  - name: aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
snapshotsEnabled: false
deployRestic: false
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
credentials:
  useSecret: true
