apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${K8S_EXP_CLUSTER_NAME}
  region: ${K8S_EXP_REGION}
  tags:
    deployment: eks-${K8S_EXP_ENVIRONMENT}

nodeGroups:
  - name: ng-1
    labels: { role: worker, cluster: cluster-eks }
    instanceType: t2.nano
    desiredCapacity: 1
    ssh:
      allow: true
