apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks
  region: eu-west-1

nodeGroups:
  - name: ng-1
    labels: { role: worker, cluster: cluster-eks }
    # https://aws.amazon.com/ec2/instance-types/
    instanceType: t2.nano
    desiredCapacity: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: m5.xlarge
  #   desiredCapacity: 2
  #   ssh:
  #     publicKeyPath: ~/.ssh/ec2_id_rsa.pub
