apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${K8S_EXP_CLUSTER_NAME}
  region: ${K8S_EXP_REGION}
  version: "1.16"
  tags:
    deployment: eks-${K8S_EXP_ENVIRONMENT}

# 1. does it really work? https://github.com/aws/containers-roadmap/issues/108#issuecomment-578109867 it didn't
# 2. can a cluster get created at all? add private net true for vpc or for nodeGroups? https://github.com/aws/containers-roadmap/issues/108#issuecomment-578109867 https://eksctl.io/usage/vpc-networking/#restricting-access-to-the-eks-kubernetes-public-api-endpoint https://github.com/weaveworks/eksctl/issues/1482
# 3. how to update cluster config? this was done here? https://github.com/aws/containers-roadmap/issues/108#issuecomment-578109867
vpc:
  publicAccessCIDRs:
    - "${my_ip}"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

# https://github.com/weaveworks/eksctl/blob/master/examples/11-cloudwatch-cluster-logging.yaml
# https://eksctl.io/usage/cloudwatch-cluster-logging/
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

nodeGroups:
  - name: ng-1
    labels: { role: worker, cluster: ${K8S_EXP_CLUSTER_NAME} }
    instanceType: t2.nano
    desiredCapacity: 1
    privateNetworking: true
    ssh:
      allow: false
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
