apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-testing
  region: eu-west-1
  version: "1.16"
  tags:
    deployment: eks-testing

vpc:
  publicAccessCIDRs:
    - "31.183.242.155/32"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

# https://github.com/weaveworks/eksctl/blob/master/examples/11-cloudwatch-cluster-logging.yaml
# https://eksctl.io/usage/cloudwatch-cluster-logging/
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

nodeGroups:
  - name: ng-1
    labels: { role: worker, cluster: eks-testing }
    # https://aws.amazon.com/ec2/instance-types/
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true
    ssh:
      allow: false
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-testing: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true
