#!/bin/bash

set -e

export K8S_EXP_REGION="eu-west-1"

if [[ "${K8S_EXP_ENVIRONMENT}" != "testing" ]] && [[ "${K8S_EXP_ENVIRONMENT}" != "production" ]]; then
  echo "Error: K8S_EXP_ENVIRONMENT should be set to testing or production"
  exit 1
fi

export K8S_EXP_CLUSTER_NAME="eks-${K8S_EXP_ENVIRONMENT}"
export K8S_EXP_VELERO_S3_BUCKET="k8s-eks-for-masters-thesis.k8s.local"

function create_s3_bucket() {
  local bucket_name=$1
  local region=$2

  if aws s3api list-buckets | jq '.Buckets[]["Name"]' | grep ${bucket_name} >/dev/null; then
    echo "S3 Bucket already exists"
  else
    echo "Creating S3 Bucket: ${bucket_name}"
    set -x
    aws s3api create-bucket --bucket ${bucket_name} --region ${region} --create-bucket-configuration LocationConstraint=${region}
    # enable s3 bucket versioning.
    # strongly recommended in: https://aws.amazon.com/blogs/compute/kubernetes-clusters-aws-kops/
    # https://kops.sigs.k8s.io/getting_started/aws
    aws s3api put-bucket-versioning --bucket ${bucket_name} --versioning-configuration Status=Enabled
    # enable s3 default encryption (AES-256, SSE-S3)
    # https://kops.sigs.k8s.io/getting_started/aws
    aws s3api put-bucket-encryption --bucket ${bucket_name} --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
    set +x
    echo "Success"
  fi
}

command="$1"
case "${command}" in
    _create)
        my_ip=$(curl https://ipinfo.io/ip 2>/dev/null)
        sed "s/\${K8S_EXP_CLUSTER_NAME}/${K8S_EXP_CLUSTER_NAME}/" cluster.tmpl.yaml > cluster1.yaml
        sed "s/\${K8S_EXP_REGION}/${K8S_EXP_REGION}/" cluster1.yaml > cluster2.yaml
        sed "s/\${K8S_EXP_ENVIRONMENT}/${K8S_EXP_ENVIRONMENT}/" cluster2.yaml > cluster3.yaml
        sed "s'\${my_ip}'${my_ip}/32'" cluster3.yaml > cluster.yaml
        rm cluster1.yaml cluster2.yaml cluster3.yaml
        # print date, so that end user can expect how much longer to wait
        date
        set -x
        time eksctl create cluster -f cluster.yaml
        ;;
    _test)
        set -x
        cd ../tests
        time bats tests.bats
        cd ../eks
        ;;
    _enable_as)
        set -x
        sed "s/\${CLUSTER_NAME}/${K8S_EXP_CLUSTER_NAME}/" ../as/cluster-autoscaler-autodiscover.tmpl.yaml > cluster-autoscaler-autodiscover.yaml
        kubectl apply -f cluster-autoscaler-autodiscover.yaml
        ;;
    _install_velero_cli)
        wget -O /tmp/velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.4.0/velero-v1.4.0-linux-amd64.tar.gz
        cd /tmp
        tar -xvf velero.tar.gz
        chmod +x velero/velero
        sudo mv velero/velero /usr/local/bin/velero
        ;;
    _enable_velero)
        create_s3_bucket ${K8S_EXP_VELERO_S3_BUCKET} ${K8S_EXP_REGION}
        set -x
        kubectl create namespace velero
        helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
        helm install velero --namespace velero -f ${PWD}/../velero/velero-chart-values.yaml \
          --set configuration.backupStorageLocation.bucket=${K8S_EXP_VELERO_S3_BUCKET} \
          --set configuration.backupStorageLocation.prefix=${K8S_EXP_ENVIRONMENT} \
          --set configuration.backupStorageLocation.config.region=${K8S_EXP_REGION} \
          --set-file credentials.secretContents.cloud=credentials-velero \
          --wait --atomic vmware-tanzu/velero
        ;;
    _delete)
        # print date, so that end user can expect how much longer to wait
        date
        set -x
        time eksctl delete cluster -f cluster.yaml --wait
        ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
esac
